blank_issues_enabled: false
contact_links:
  - name: Glos Community Pachca
    url: https://app.pachca.com/join?invite_token=EakW3nIgma_ezqFc&company_name=Glos+Community&company_id=416542
    about: Get free help from the Glos community
  - name: Glos Community Discussion
    url: https://github.com/MiCkEyZzZ/glos/discussions
    about: Get free help from the Glos community
